export const currentDate = {
  iso: '2026-08-04',
  display: '2026 年 8 月 4 日',
  weekday: '周二',
  timezone: 'Asia/Singapore',
}

export const cycle = {
  id: '2026-C01',
  title: 'Agent & Post-Training',
  week: 'W01',
  weekRange: '08/04–08/09',
  question:
    '后训练、工具调用、记忆与反馈机制如何共同塑造 LLM Agent 的可靠行为，其主要瓶颈来自训练目标、交互环境还是评测方式？',
  hours: '5–6 小时',
  success: [
    { label: '精读', current: 0, target: 10 },
    { label: '扫描', current: 0, target: 12 },
    { label: '概念笔记', current: 0, target: 4 },
    { label: '周结', current: 0, target: 9 },
  ],
}

export const currentPaper = {
  id: 'ouyang_training_2022',
  title: 'Training Language Models to Follow Instructions with Human Feedback',
  shortTitle: 'InstructGPT',
  authors: 'Ouyang et al.',
  year: 2022,
  venue: 'NeurIPS',
  status: 'queued',
  statusLabel: '待阅读',
  depth: 'deep',
  depthLabel: '精读',
  week: 'W02',
  scheduled: '08/10–08/16',
  nextReview: '08/05',
  zoteroKey: 'AQQPLG9Z',
  topics: ['post-training', 'RLHF', 'alignment'],
}

export const checkpoints = [
  { id: 'question', label: '研究问题', hint: '问题与动机' },
  { id: 'method', label: '方法与推导', hint: '输入、目标与约束' },
  { id: 'evidence', label: '实验与证据', hint: '结果与定位' },
  { id: 'limits', label: '局限与反例', hint: '边界与失效条件' },
  { id: 'connections', label: '知识连接', hint: '前置、冲突与延伸' },
]

export const readingPlan = [
  { duration: '15m', title: '定位问题', detail: '明确研究问题与动机' },
  { duration: '45m', title: '方法与证据', detail: '核对关键假设与实验' },
  { duration: '30m', title: '闭卷复述', detail: '脱离原文重建论证' },
]

export const proposedConnections = [
  {
    id: 'rlhf-pipeline',
    title: 'SFT → 偏好数据 → RM → PPO',
    lane: '训练目标',
    locator: 'Figure 2 · p.6',
    prompt: '这一数据链如何决定最终策略学到的偏好代理？',
  },
  {
    id: 'capability-retention',
    title: 'KL / pretraining mix → 能力保留',
    lane: '训练目标',
    locator: 'Equation 2 · p.9',
    prompt: '两种约束分别限制了什么，能否推出更广义的可靠性？',
  },
  {
    id: 'agent-mdp',
    title: '单步 bandit → Agent as MDP',
    lane: '交互环境',
    locator: 'Section 3.5 · p.9',
    prompt: '多轮工具交互会增加哪些状态与 credit assignment 问题？',
  },
  {
    id: 'evaluator-agreement',
    title: 'Evaluator agreement ≠ 广义可靠性',
    lane: '评测方式',
    locator: 'Sections 5.2–5.3 · pp.18–19',
    prompt: '同一抽样框内的偏好泛化能支持多大范围的外推？',
  },
]

export const papers = [
  currentPaper,
  {
    id: 'schulman_ppo_2017',
    title: 'Proximal Policy Optimization Algorithms',
    shortTitle: 'PPO',
    authors: 'Schulman et al.',
    year: 2017,
    venue: 'arXiv',
    status: 'planned',
    statusLabel: '计划扫描',
    depth: 'scan',
    depthLabel: '扫描',
    week: 'W02',
    topics: ['reinforcement-learning', 'optimization'],
  },
  {
    id: 'rafailov_dpo_2023',
    title: 'Direct Preference Optimization: Your Language Model is Secretly a Reward Model',
    shortTitle: 'DPO',
    authors: 'Rafailov et al.',
    year: 2023,
    venue: 'NeurIPS',
    status: 'planned',
    statusLabel: '计划精读',
    depth: 'deep',
    depthLabel: '精读',
    week: 'W03',
    topics: ['preference-optimization', 'alignment'],
  },
  {
    id: 'deepseek_r1_2025',
    title: 'DeepSeek-R1: Incentivizing Reasoning Capability in LLMs via Reinforcement Learning',
    shortTitle: 'DeepSeek-R1',
    authors: 'DeepSeek-AI',
    year: 2025,
    venue: 'arXiv',
    status: 'planned',
    statusLabel: '计划精读',
    depth: 'deep',
    depthLabel: '精读',
    week: 'W04',
    topics: ['reasoning', 'GRPO', 'post-training'],
  },
  {
    id: 'yao_react_2023',
    title: 'ReAct: Synergizing Reasoning and Acting in Language Models',
    shortTitle: 'ReAct',
    authors: 'Yao et al.',
    year: 2023,
    venue: 'ICLR',
    status: 'planned',
    statusLabel: '计划精读',
    depth: 'deep',
    depthLabel: '精读',
    week: 'W05',
    topics: ['agent', 'tool-use', 'reasoning'],
  },
  {
    id: 'schick_toolformer_2023',
    title: 'Toolformer: Language Models Can Teach Themselves to Use Tools',
    shortTitle: 'Toolformer',
    authors: 'Schick et al.',
    year: 2023,
    venue: 'NeurIPS',
    status: 'planned',
    statusLabel: '计划精读',
    depth: 'deep',
    depthLabel: '精读',
    week: 'W06',
    topics: ['tool-use', 'self-supervision'],
  },
  {
    id: 'shinn_reflexion_2023',
    title: 'Reflexion: Language Agents with Verbal Reinforcement Learning',
    shortTitle: 'Reflexion',
    authors: 'Shinn et al.',
    year: 2023,
    venue: 'NeurIPS',
    status: 'planned',
    statusLabel: '计划精读',
    depth: 'deep',
    depthLabel: '精读',
    week: 'W07',
    topics: ['agent', 'reflection', 'memory'],
  },
  {
    id: 'packer_memgpt_2023',
    title: 'MemGPT: Towards LLMs as Operating Systems',
    shortTitle: 'MemGPT',
    authors: 'Packer et al.',
    year: 2023,
    venue: 'arXiv',
    status: 'planned',
    statusLabel: '计划精读',
    depth: 'deep',
    depthLabel: '精读',
    week: 'W08',
    topics: ['memory', 'agent-systems'],
  },
  {
    id: 'liu_agentbench_2023',
    title: 'AgentBench: Evaluating LLMs as Agents',
    shortTitle: 'AgentBench',
    authors: 'Liu et al.',
    year: 2023,
    venue: 'ICLR',
    status: 'planned',
    statusLabel: '计划精读',
    depth: 'deep',
    depthLabel: '精读',
    week: 'W09',
    topics: ['evaluation', 'agent', 'benchmark'],
  },
  {
    id: 'yao_tau_bench_2024',
    title: 'τ-bench: A Benchmark for Tool-Agent-User Interaction in Real-World Domains',
    shortTitle: 'τ-bench',
    authors: 'Yao et al.',
    year: 2024,
    venue: 'arXiv',
    status: 'planned',
    statusLabel: '计划精读',
    depth: 'deep',
    depthLabel: '精读',
    week: 'W10',
    topics: ['evaluation', 'tool-use', 'reliability'],
  },
]

export const weeklyCommitments = [
  { id: 'repo', label: '完成仓库与 GitHub 初始化', done: true },
  { id: 'zotero', label: '建立 Zotero 集合与自动导出', done: true },
  { id: 'map', label: '建立知识地图骨架和候选队列', done: true },
  { id: 'baseline', label: '完成不查资料的基线自测', done: false },
]

export const synthesisQuestions = [
  '训练目标的代理偏差如何沿着 Agent 轨迹被放大？',
  '环境反馈需要满足什么条件，才能支持可靠的 credit assignment？',
  'pass^k 等指标与真实多轮可靠性之间存在什么缺口？',
  '外部记忆改变的是策略能力、上下文状态，还是评测可见性？',
  '哪些可靠性失败来自模型，哪些来自工具与环境接口？',
]
