#!/usr/bin/env python3
"""AI Reading Lab automation with no third-party runtime dependencies."""

from __future__ import annotations

import argparse
import datetime as dt
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable
from urllib.parse import unquote


ROOT = Path(__file__).resolve().parents[1]
FRONTMATTER_BOUNDARY = "---"
GENERATED_NOTICE = "<!-- Generated by scripts/lab.py. Run `python3 scripts/lab.py build`; do not edit manually. -->"
REQUIRED_FIELDS = {
    "zotero_key",
    "citekey",
    "status",
    "depth",
    "topics",
    "cycle",
    "created",
    "updated",
    "next_review",
}
DATE_FIELDS = {"created", "updated", "next_review"}
ZOTERO_KEY_RE = re.compile(r"^[A-Z0-9]{8}$")
CITEKEY_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_.:-]*$")
BIB_ENTRY_RE = re.compile(r"@(?:article|book|inbook|incollection|inproceedings|misc|phdthesis|techreport|unpublished)\s*\{\s*([^,\s]+)", re.I)
MARKDOWN_LINK_RE = re.compile(r"(?<!!)\[[^\]]*\]\(([^)]+)\)")
SECRET_PATTERNS = {
    "OpenAI API key": re.compile(r"\bsk-[A-Za-z0-9_-]{32,}\b"),
    "GitHub token": re.compile(r"\b(?:github_pat_|ghp_)[A-Za-z0-9_]{20,}\b"),
    "private key": re.compile(r"-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----"),
}
LOCAL_PATH_PATTERNS = {
    "macOS user path": re.compile("/" + r"Users/[^/\s]+/"),
    "Linux home path": re.compile("/" + r"home/[^/\s]+/"),
    "Windows user path": re.compile(r"[A-Za-z]:\\\\Users\\\\[^\\\\\s]+\\\\"),
}
FORBIDDEN_SUFFIXES = {".pdf", ".sqlite", ".sqlite-journal", ".xpi"}
FORBIDDEN_DIR_NAMES = {"storage", "attachments"}

REQUIRED_SECTIONS = {
    "scan": {
        "一句话结论",
        "中文摘要",
        "English Summary",
    },
    "normal": {
        "一句话结论",
        "中文摘要",
        "English Summary",
        "研究问题",
        "实验与证据",
        "局限与反例",
        "知识连接",
    },
    "deep": {
        "一句话结论",
        "中文摘要",
        "English Summary",
        "研究问题",
        "假设与适用边界",
        "核心方法与推导",
        "实验与证据",
        "局限与反例",
        "知识连接",
        "工程意义",
        "疑问与新想法",
        "主动回忆",
    },
}


@dataclass(frozen=True)
class PaperNote:
    path: Path
    metadata: dict[str, Any]
    body: str


def parse_scalar(value: str) -> Any:
    value = value.strip()
    if not value:
        return ""
    if value.startswith("[") and value.endswith("]"):
        inner = value[1:-1].strip()
        if not inner:
            return []
        return [parse_scalar(part) for part in inner.split(",")]
    if value.startswith(('"', "'")) and value.endswith(value[0]):
        return value[1:-1]
    if value in {"true", "True"}:
        return True
    if value in {"false", "False"}:
        return False
    if value in {"null", "Null", "NULL", "~"}:
        return None
    try:
        return int(value)
    except ValueError:
        return value


def parse_simple_yaml(text: str) -> dict[str, Any]:
    data: dict[str, Any] = {}
    for number, raw in enumerate(text.splitlines(), start=1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if ":" not in line:
            raise ValueError(f"line {number}: expected key: value")
        key, value = line.split(":", 1)
        key = key.strip()
        if not key:
            raise ValueError(f"line {number}: empty key")
        data[key] = parse_scalar(value)
    return data


def load_config(root: Path = ROOT) -> dict[str, Any]:
    path = root / "config/project.yaml"
    return parse_simple_yaml(path.read_text(encoding="utf-8"))


def parse_frontmatter(path: Path) -> PaperNote:
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()
    if not lines or lines[0].strip() != FRONTMATTER_BOUNDARY:
        raise ValueError("missing opening YAML frontmatter boundary")
    try:
        end = next(i for i, line in enumerate(lines[1:], start=1) if line.strip() == FRONTMATTER_BOUNDARY)
    except StopIteration as exc:
        raise ValueError("missing closing YAML frontmatter boundary") from exc
    metadata = parse_simple_yaml("\n".join(lines[1:end]))
    return PaperNote(path=path, metadata=metadata, body="\n".join(lines[end + 1 :]))


def paper_notes(root: Path = ROOT) -> list[PaperNote]:
    notes: list[PaperNote] = []
    for path in sorted((root / "notes/papers").glob("*.md")):
        notes.append(parse_frontmatter(path))
    return notes


def bibtex_keys(root: Path = ROOT) -> list[str]:
    path = root / "references/library.bib"
    if not path.exists():
        return []
    return BIB_ENTRY_RE.findall(path.read_text(encoding="utf-8"))


def section_names(body: str) -> set[str]:
    return {
        match.group(1).strip()
        for match in re.finditer(r"^##\s+(.+?)\s*$", body, flags=re.MULTILINE)
    }


def section_text(body: str, section: str) -> str:
    pattern = re.compile(
        rf"^##\s+{re.escape(section)}\s*$\n(.*?)(?=^##\s+|\Z)",
        flags=re.MULTILINE | re.DOTALL,
    )
    match = pattern.search(body)
    if not match:
        return ""
    text = re.sub(r"<!--.*?-->", "", match.group(1), flags=re.DOTALL)
    return text.strip()


def validate_paper_note(note: PaperNote, config: dict[str, Any], known_keys: set[str]) -> list[str]:
    errors: list[str] = []
    rel = note.path.as_posix()
    meta = note.metadata
    missing = sorted(REQUIRED_FIELDS - meta.keys())
    if missing:
        errors.append(f"{rel}: missing frontmatter fields: {', '.join(missing)}")
        return errors

    citekey = str(meta["citekey"])
    zotero_key = str(meta["zotero_key"])
    status = str(meta["status"])
    depth = str(meta["depth"])

    if not CITEKEY_RE.fullmatch(citekey):
        errors.append(f"{rel}: invalid citekey {citekey!r}")
    if note.path.stem != citekey:
        errors.append(f"{rel}: filename must equal citekey ({citekey}.md)")
    if not ZOTERO_KEY_RE.fullmatch(zotero_key):
        errors.append(f"{rel}: zotero_key must be an 8-character Zotero item key")
    if citekey not in known_keys:
        errors.append(f"{rel}: citekey {citekey!r} is absent from references/library.bib")
    if status not in set(config["statuses"]):
        errors.append(f"{rel}: invalid status {status!r}")
    if depth not in set(config["depths"]):
        errors.append(f"{rel}: invalid depth {depth!r}")
    if not isinstance(meta["topics"], list):
        errors.append(f"{rel}: topics must be a YAML inline list")
    if not re.fullmatch(r"\d{4}-C\d{2}", str(meta["cycle"])):
        errors.append(f"{rel}: cycle must look like 2026-C01")
    for field in DATE_FIELDS:
        try:
            dt.date.fromisoformat(str(meta[field]))
        except ValueError:
            errors.append(f"{rel}: {field} must be YYYY-MM-DD")

    headings = section_names(note.body)
    if "Abstract" in headings:
        errors.append(f"{rel}: use an original English Summary; do not add an Abstract section")
    required = REQUIRED_SECTIONS.get(depth, set())
    absent = sorted(required - headings)
    if absent:
        errors.append(f"{rel}: missing sections for {depth}: {', '.join(absent)}")

    if status in {"read", "synthesized", "revisit", "archived"}:
        zh = section_text(note.body, "中文摘要")
        en = section_text(note.body, "English Summary")
        zh_chars = len(re.sub(r"\s+", "", zh))
        en_words = len(re.findall(r"\b[\w'-]+\b", en))
        if not 150 <= zh_chars <= 300:
            errors.append(f"{rel}: 中文摘要 must contain 150–300 non-space characters; found {zh_chars}")
        if not 100 <= en_words <= 180:
            errors.append(f"{rel}: English Summary must contain 100–180 words; found {en_words}")
        for heading in required:
            content = section_text(note.body, heading)
            if not content or content == "TODO":
                errors.append(f"{rel}: completed note still has an empty/TODO section: {heading}")
    return errors


def render_dashboard(root: Path, config: dict[str, Any], notes: list[PaperNote], today: dt.date) -> str:
    status_counts = {status: 0 for status in config["statuses"]}
    depth_counts = {depth: 0 for depth in config["depths"]}
    overdue: list[PaperNote] = []
    for note in notes:
        status = str(note.metadata.get("status", ""))
        depth = str(note.metadata.get("depth", ""))
        if status in status_counts:
            status_counts[status] += 1
        if depth in depth_counts:
            depth_counts[depth] += 1
        if status != "archived":
            try:
                if dt.date.fromisoformat(str(note.metadata.get("next_review"))) < today:
                    overdue.append(note)
            except ValueError:
                pass

    lines = [
        GENERATED_NOTICE,
        "",
        "# Dashboard",
        "",
        f"- As of: {today.isoformat()} ({config['timezone']})",
        f"- Active cycle: [{config['active_cycle']}]({config['active_cycle_dir']}/PLAN.md)",
        f"- Weekly budget: {config['weekly_hours']} hours",
        "- [Paper and concept index](notes/INDEX.md)",
        "",
        "## Reading state",
        "",
        "| Status | Count |",
        "|---|---:|",
    ]
    lines.extend(f"| `{status}` | {status_counts[status]} |" for status in config["statuses"])
    lines.extend(["", "| Depth | Count |", "|---|---:|"])
    lines.extend(f"| `{depth}` | {depth_counts[depth]} |" for depth in config["depths"])
    lines.extend(["", "## Reviews due", ""])
    if overdue:
        for note in sorted(overdue, key=lambda item: str(item.metadata["next_review"])):
            citekey = note.metadata["citekey"]
            rel = note.path.relative_to(root).as_posix()
            lines.append(f"- {note.metadata['next_review']}: [{citekey}]({rel})")
    else:
        lines.append("No overdue reviews.")
    lines.extend(["", "## Guardrails", "", f"- Active `reading` limit: {config['deep_reading_wip_limit']}", f"- Deep queued limit: {config['deep_queue_limit']}", "- New directions are reviewed only in the weekly review.", ""])
    return "\n".join(lines)


def render_index(root: Path, notes: list[PaperNote]) -> str:
    lines = [
        GENERATED_NOTICE,
        "",
        "# Notes Index",
        "",
        "## Paper notes",
        "",
    ]
    if notes:
        lines.extend(["| Citekey | Status | Depth | Topics | Next review |", "|---|---|---|---|---|"])
        for note in sorted(notes, key=lambda item: str(item.metadata.get("citekey", ""))):
            meta = note.metadata
            topics = ", ".join(str(topic) for topic in meta.get("topics", []))
            link = f"papers/{note.path.name}"
            lines.append(f"| [{meta.get('citekey', note.path.stem)}]({link}) | `{meta.get('status', '')}` | `{meta.get('depth', '')}` | {topics} | {meta.get('next_review', '')} |")
    else:
        lines.append("No paper notes yet. Add the first note after its Zotero item and citekey are ready.")
    lines.extend(["", "## Concept notes", ""])
    concepts = sorted((root / "notes/concepts").glob("*.md"))
    if concepts:
        for path in concepts:
            title = next((line[2:].strip() for line in path.read_text(encoding="utf-8").splitlines() if line.startswith("# ")), path.stem)
            lines.append(f"- [{title}](concepts/{path.name})")
    else:
        lines.append("No concept notes yet.")
    lines.extend(["", "## Knowledge maps", ""])
    maps = sorted((root / "notes/maps").glob("*.md"))
    if maps:
        for path in maps:
            title = next((line[2:].strip() for line in path.read_text(encoding="utf-8").splitlines() if line.startswith("# ")), path.stem)
            lines.append(f"- [{title}](maps/{path.name})")
    else:
        lines.append("No knowledge maps yet.")
    lines.append("")
    return "\n".join(lines)


def build(root: Path = ROOT, today: dt.date | None = None) -> None:
    today = today or dt.date.today()
    config = load_config(root)
    notes = paper_notes(root)
    (root / "DASHBOARD.md").write_text(render_dashboard(root, config, notes, today), encoding="utf-8")
    (root / "notes/INDEX.md").write_text(render_index(root, notes), encoding="utf-8")


def relative_markdown_links(path: Path) -> Iterable[str]:
    text = path.read_text(encoding="utf-8")
    for raw in MARKDOWN_LINK_RE.findall(text):
        target = raw.strip().split(maxsplit=1)[0].strip("<>")
        if target.startswith(("http://", "https://", "mailto:", "#")):
            continue
        yield unquote(target.split("#", 1)[0])


def check_links(root: Path) -> list[str]:
    errors: list[str] = []
    for path in sorted(root.rglob("*.md")):
        if ".git" in path.parts:
            continue
        for target in relative_markdown_links(path):
            if not target:
                continue
            resolved = (path.parent / target).resolve()
            try:
                resolved.relative_to(root.resolve())
            except ValueError:
                errors.append(f"{path.relative_to(root)}: link escapes repository: {target}")
                continue
            if not resolved.exists():
                errors.append(f"{path.relative_to(root)}: broken relative link: {target}")
    return errors


def check_forbidden_files(root: Path, max_bytes: int) -> list[str]:
    errors: list[str] = []
    for path in sorted(root.rglob("*")):
        if not path.is_file() or ".git" in path.parts:
            continue
        rel = path.relative_to(root)
        lower_name = path.name.lower()
        if path.suffix.lower() in FORBIDDEN_SUFFIXES:
            errors.append(f"{rel}: forbidden file type {path.suffix}")
        if lower_name == ".env" or lower_name.startswith(".env.") and lower_name != ".env.example":
            errors.append(f"{rel}: local environment/secrets file must not be committed")
        if any(part.lower() in FORBIDDEN_DIR_NAMES for part in rel.parts[:-1]):
            errors.append(f"{rel}: Zotero attachment directory is forbidden")
        if path.stat().st_size > max_bytes:
            errors.append(f"{rel}: file exceeds {max_bytes} bytes")
        try:
            content = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        for label, pattern in SECRET_PATTERNS.items():
            if pattern.search(content):
                errors.append(f"{rel}: possible {label} detected")
        for label, pattern in LOCAL_PATH_PATTERNS.items():
            if pattern.search(content):
                errors.append(f"{rel}: possible local absolute path detected ({label})")
    return errors


def run_checks(root: Path = ROOT, today: dt.date | None = None) -> tuple[list[str], list[str]]:
    today = today or dt.date.today()
    errors: list[str] = []
    warnings: list[str] = []
    try:
        config = load_config(root)
    except (OSError, ValueError) as exc:
        return [f"config/project.yaml: {exc}"], warnings

    keys = bibtex_keys(root)
    duplicate_keys = sorted({key for key in keys if keys.count(key) > 1})
    if duplicate_keys:
        errors.append(f"references/library.bib: duplicate citekeys: {', '.join(duplicate_keys)}")

    try:
        notes = paper_notes(root)
    except ValueError as exc:
        errors.append(f"notes/papers: {exc}")
        notes = []
    for note in notes:
        errors.extend(validate_paper_note(note, config, set(keys)))

    reading = [note for note in notes if note.metadata.get("status") == "reading"]
    if len(reading) > int(config["deep_reading_wip_limit"]):
        errors.append(f"reading WIP limit exceeded: {len(reading)} > {config['deep_reading_wip_limit']}")
    queued_deep = [note for note in notes if note.metadata.get("status") == "queued" and note.metadata.get("depth") == "deep"]
    if len(queued_deep) > int(config["deep_queue_limit"]):
        errors.append(f"deep queue limit exceeded: {len(queued_deep)} > {config['deep_queue_limit']}")

    for note in notes:
        if note.metadata.get("status") != "archived":
            try:
                due = dt.date.fromisoformat(str(note.metadata.get("next_review")))
                if due < today:
                    warnings.append(f"review overdue: {note.metadata.get('citekey')} since {due}")
            except ValueError:
                pass

    errors.extend(check_links(root))
    errors.extend(check_forbidden_files(root, int(config["max_file_bytes"])))

    expected = {
        root / "DASHBOARD.md": render_dashboard(root, config, notes, today),
        root / "notes/INDEX.md": render_index(root, notes),
    }
    for path, content in expected.items():
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            errors.append(
                f"{path.relative_to(root)}: generated file is stale; "
                "run `python3 scripts/lab.py build`"
            )
    return errors, warnings


def command_check(root: Path = ROOT) -> int:
    errors, warnings = run_checks(root)
    for warning in warnings:
        print(f"WARNING: {warning}")
    if errors:
        for error in errors:
            print(f"ERROR: {error}")
        print(f"check failed with {len(errors)} error(s)")
        return 1
    print(f"check passed ({len(warnings)} warning(s))")
    return 0


def new_paper(citekey: str, root: Path = ROOT) -> Path:
    if not CITEKEY_RE.fullmatch(citekey):
        raise ValueError("CITEKEY must use letters, digits, dot, underscore, colon, or hyphen")
    destination = root / "notes/papers" / f"{citekey}.md"
    if destination.exists():
        raise FileExistsError(f"paper note already exists: {destination.relative_to(root)}")
    config = load_config(root)
    today = dt.date.today()
    template = (root / "templates/paper-note.md").read_text(encoding="utf-8")
    content = (
        template.replace("{{ZOTERO_KEY}}", "TODO")
        .replace("{{CITEKEY}}", citekey)
        .replace("{{CYCLE}}", str(config["active_cycle"]))
        .replace("{{DATE}}", today.isoformat())
        .replace("{{NEXT_REVIEW}}", (today + dt.timedelta(days=1)).isoformat())
    )
    destination.write_text(content, encoding="utf-8")
    return destination


def week_range(config: dict[str, Any], week: int) -> tuple[dt.date, dt.date]:
    if not 1 <= week <= 99:
        raise ValueError("WEEK must be between 1 and 99")
    cycle_start = dt.date.fromisoformat(str(config["cycle_start"]))
    cycle_end = dt.date.fromisoformat(str(config["cycle_end"]))
    first_end = cycle_start + dt.timedelta(days=(6 - cycle_start.weekday()) % 7)
    if week == 1:
        start, end = cycle_start, min(first_end, cycle_end)
    else:
        start = first_end + dt.timedelta(days=1 + (week - 2) * 7)
        end = min(start + dt.timedelta(days=6), cycle_end)
    if start > cycle_end:
        raise ValueError(f"W{week:02d} begins after the active cycle ends")
    return start, end


def new_week(week: int, root: Path = ROOT) -> Path:
    config = load_config(root)
    start, end = week_range(config, week)
    destination = root / str(config["active_cycle_dir"]) / "weeks" / f"W{week:02d}.md"
    if destination.exists():
        raise FileExistsError(f"weekly note already exists: {destination.relative_to(root)}")
    template = (root / "templates/weekly.md").read_text(encoding="utf-8")
    content = (
        template.replace("{{WEEK}}", f"W{week:02d}")
        .replace("{{START}}", start.isoformat())
        .replace("{{END}}", end.isoformat())
    )
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(content, encoding="utf-8")
    return destination


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)
    subparsers.add_parser("build", help="regenerate Dashboard and note index")
    subparsers.add_parser("check", help="validate repository invariants")
    paper_parser = subparsers.add_parser("new-paper", help="create a paper note from the template")
    paper_parser.add_argument("citekey")
    week_parser = subparsers.add_parser("new-week", help="create a weekly note from the template")
    week_parser.add_argument("week", type=int)
    args = parser.parse_args(argv)

    try:
        if args.command == "build":
            build()
            print("generated DASHBOARD.md and notes/INDEX.md")
            return 0
        if args.command == "check":
            return command_check()
        if args.command == "new-paper":
            path = new_paper(args.citekey)
            print(path.relative_to(ROOT))
            return 0
        if args.command == "new-week":
            path = new_week(args.week)
            print(path.relative_to(ROOT))
            return 0
    except (OSError, ValueError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
